src/ComicBookGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

src/ComicBookGallery/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public Series Series { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }

        public string DisplayText
        {
          
            get
            {
                var series = Series; // Creating a local variable of the class Series
                if (series != null) // Checks if Series is not equal to null
                {
                    return Series.Title + " #" + IssueNumber; // Return matched Title and IssueNumber
                }
                else
                {
                    return null;
                }
            }
        }

        
        public string CoverImageFileName
        {
            get
            {
                var series = Series; // Create a variable of the class Series
                if (series != null)
                {
                    // series-title-issuenumber.jpg
                    return Series.Title.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
                }
                else
                {
                    return null;
                }
                

            }
        }
        
    }
}

src/ComicBookGallery/Models/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Series
    {
        public int Id { get; set; } // Sets ID for the Series
        public string Title { get; set; } // Sets Title for the Series
        public string DescriptionHtml { get; set; } // Sets the Description for the Series
        public ComicBook[] Issues {get; set;} // Containing the ComicBook objects per issue
    }
}

src/ComicBookGallery/Controllers/ComicBooksController.cs
using ComicBookGallery.Data;
using ComicBookGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicBookGallery.Controllers
{
    public class ComicBooksController : Controller
    {
        // Private instance of the class ComicBookRepository set to null
        private ComicBookRepository _comicBookRepository = null;

        // Creates a new ComicBookrepository set to the private instance
        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository();
        }

        // Builds the list of comic books to the view Index
        public ActionResult Index()
        {
            var comicBooks = _comicBookRepository.GetComicBooks();

            return View(comicBooks);

        }


        public ActionResult Detail(int? id) // MVC can pass null if ID isn't provided.
        {
            if( id == null)
            {
                return HttpNotFound();
            }
            // Returns the ID value from the repository
            var comicBook = _comicBookRepository.GetComicBook(id.Value);

            return View(comicBook);
        }
    }
}

src/ComicBookGallery/Controllers/SeriesController.cs
using ComicBookGallery.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicBookGallery.Controllers
{
    public class SeriesController : Controller
    {
        private SeriesRepository _seriesRepository = null;

        public SeriesController()
        {
            _seriesRepository = new SeriesRepository();
        }

        public ActionResult Index()
        {
            var series = _seriesRepository.GetSeries();

            return View(series);
        }

        public ActionResult Detail(int? id) // Makes i 'Nullable'
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Loops the Series[] to find matching ID
            var series = _seriesRepository.GetSeriesDetail(id.Value);

            return View(series);
        }
    }
}

src/ComicBookGallery/Views/ComicBooks/Detail.cshtml
@model ComicBookGallery.Models.ComicBook

@{
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
}


<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @(Model.Series != null ? Model.Series.Title: "N/A")</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @(Model.Favorite ? "Yes" : "No")</h5>
            @if (Model.Artists.Length > 0)
            {
                <h5>Artists:</h5>
                <div>
                    <ul>
                        @foreach (var artist in Model.Artists)
                        {
                            <li>@artist.Role: @artist.Name</li>

                        }
                    </ul>
                </div>
            }
        </div>

        <h5>Description:</h5>
        <div>@Html.Raw(Model.DescriptionHtml)</div>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.CoverImageFileName" class="img-responsive" />
    </div>
</div>

src/ComicBookGallery/Views/ComicBooks/Index.cshtml
@model ComicBookGallery.Models.ComicBook[]

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var comicBook in Model)
    {
        <div class="col-md-3">
            <h4>@Html.ActionLink(comicBook.DisplayText,"Detail", new { id = comicBook.Id })</h4>
            <a href="@Url.Action("Detail", new { id = comicBook.Id })">
            <img src="/Images/@comicBook.CoverImageFileName"
                    alt="@comicBook.CoverImageFileName"
                    class="img-responsive" />
             </a>
        </div>
    }
</div>

src/ComicBookGallery/Views/Series/Detail.cshtml
@model ComicBookGallery.Models.Series

@{
    ViewBag.Title = Model.Title;
    ViewBag.ShowBackBar = true;
}

<h2>@ViewBag.Title</h2>

    <div class="well">
        <h5>Description</h5>
        <div>
            @Html.Raw(Model.DescriptionHtml)
        </div>
    </div>

    <h4>Comic Books Available in This Series</h4>

    <div class="row">
        @foreach (var comicBook in Model.Issues)
        {
            <div class="col-md-3">
                <h4>@Html.ActionLink(comicBook.DisplayText, "Detail", "ComicBooks", new { id = comicBook.Id })</h4>
                <a href="@Url.Action("Detail", "ComicBooks", new { id = comicBook.Id })">
                    <img src="/Images/@comicBook.CoverImageFileName"
                         alt="@comicBook.CoverImageFileName"
                         class="img-responsive" />
                </a>
            </div>
        }
    </div>

src/ComicBookGallery/Views/Series/Index.cshtml
@model ComicBookGallery.Models.Series[]

@{
    ViewBag.Title = "Series";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <ul class="series-list">
            @foreach(var series in Model)
            {
                <li>
                    <h4>@Html.ActionLink(@series.Title, "Detail", new { id = series.Id })</h4>
                </li>
            }
        </ul>
    </div>
</div>

src/ComicBookGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Comic Books", "Index", "ComicBooks")</li>
                    <li>@Html.ActionLink("Series", "Index", "Series")</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Calls method ShowBackBar, if its null or true -->
    @if ( ViewBag.ShowBackBar != null && ViewBag.ShowBackBar )
        {
            <div class="backbar">
                <div class="container">
                    <!-- Linktext, ActionName(return to Index), routevalue, html object  -->
                    <a href="~/Series/" class="btn btn-default">Return To List</a>
                    
                </div>
            </div>
        }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>